-- DIP-FP-107: Prayer Leader and Food Assignment fields on events
--
-- Both always-optional, no event-type gating, per the user's explicit direction. Purely
-- informational assignment metadata — handle_event_scheduling() is untouched, and neither field
-- is templated onto occurrences generated by create_event_series_with_audit() or
-- convert_event_to_series_with_audit() (deliberate scope boundary, not an oversight — see PR).
--
-- Confirmed live before writing this (nothing assumed from a prior snapshot):
--   - Full events column list (id, tenant_id, event_type_id, name, status, start_datetime,
--     end_datetime, location_name, target, created_at, updated_at, version, talk_id,
--     location_address, location_url, recurrence_series_id) — matches expectations.
--   - insert_event_with_audit()/update_event_with_audit()'s exact current parameter lists and
--     RETURNS TABLE column sets (both include location_address/location_url per PR #49) —
--     confirmed via pg_get_function_arguments/pg_get_function_result, not assumed.
--   - validate_event_talk_id()'s exact body — mirrored below for prayer_leader_member_id.
--   - target has no write-time cross-tenant trigger (only trigger_event_scheduling reads it,
--     at roster-materialization time) — confirmed via the full trigger list on events. This
--     migration deliberately applies the same precedent to food_assignment: no new trigger.

ALTER TABLE events ADD COLUMN IF NOT EXISTS prayer_leader_member_id UUID REFERENCES members(id);
ALTER TABLE events ADD COLUMN IF NOT EXISTS food_assignment JSONB;


-- ==============================================================
-- SECTION 1: cross-tenant trigger for prayer_leader_member_id
-- Mirrors validate_event_talk_id() exactly — same pattern, different column.
-- ==============================================================

CREATE OR REPLACE FUNCTION public.validate_event_prayer_leader_tenant_scope()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
BEGIN
  IF NEW.prayer_leader_member_id IS NOT NULL THEN
    IF NOT EXISTS (
      SELECT 1 FROM members
      WHERE id = NEW.prayer_leader_member_id AND tenant_id = NEW.tenant_id AND deleted_at IS NULL
    ) THEN
      RAISE EXCEPTION 'events.prayer_leader_member_id % is invalid, soft-deleted, or belongs to a different tenant', NEW.prayer_leader_member_id;
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trigger_validate_event_prayer_leader_tenant_scope ON events;
CREATE TRIGGER trigger_validate_event_prayer_leader_tenant_scope
BEFORE INSERT OR UPDATE ON events
FOR EACH ROW EXECUTE FUNCTION validate_event_prayer_leader_tenant_scope();


-- ==============================================================
-- SECTION 2: extend insert_event_with_audit()/update_event_with_audit()
-- RETURNS TABLE column set is changing again — DROP FUNCTION IF EXISTS with the exact current
-- signature is required before CREATE OR REPLACE (Postgres rejects an output-column-set change
-- otherwise; the same lesson already documented in the Core Admin Surface DIP).
-- ==============================================================

DROP FUNCTION IF EXISTS public.insert_event_with_audit(UUID, UUID, TEXT, TIMESTAMPTZ, TIMESTAMPTZ, TEXT, TEXT, TEXT, JSONB, UUID, UUID);
DROP FUNCTION IF EXISTS public.update_event_with_audit(UUID, UUID, JSONB, UUID);

CREATE OR REPLACE FUNCTION public.insert_event_with_audit(
    p_tenant_id UUID,
    p_event_type_id UUID,
    p_name TEXT,
    p_start_datetime TIMESTAMPTZ,
    p_end_datetime TIMESTAMPTZ,
    p_location_name TEXT,
    p_location_address TEXT,
    p_location_url TEXT,
    p_target JSONB,
    p_talk_id UUID,
    p_prayer_leader_member_id UUID,
    p_food_assignment JSONB,
    p_actor_member_id UUID
)
RETURNS TABLE (
    id UUID, name TEXT, status TEXT, start_datetime TIMESTAMPTZ,
    end_datetime TIMESTAMPTZ, location_name TEXT, location_address TEXT, location_url TEXT,
    target JSONB, talk_id UUID, prayer_leader_member_id UUID, food_assignment JSONB, created_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_row events%ROWTYPE;
BEGIN
  INSERT INTO events (
    tenant_id, event_type_id, name, status, start_datetime, end_datetime,
    location_name, location_address, location_url, target, talk_id,
    prayer_leader_member_id, food_assignment
  ) VALUES (
    p_tenant_id, p_event_type_id, p_name, 'DRAFT', p_start_datetime, p_end_datetime,
    p_location_name, p_location_address, p_location_url, p_target, p_talk_id,
    p_prayer_leader_member_id, p_food_assignment
  )
  RETURNING * INTO v_row;

  PERFORM write_audit_log(p_tenant_id, 'event', v_row.id, 'create', p_actor_member_id, NULL, to_jsonb(v_row));

  RETURN QUERY SELECT
    v_row.id, v_row.name, v_row.status, v_row.start_datetime,
    v_row.end_datetime, v_row.location_name, v_row.location_address, v_row.location_url,
    v_row.target, v_row.talk_id, v_row.prayer_leader_member_id, v_row.food_assignment, v_row.created_at;
END;
$$;


CREATE OR REPLACE FUNCTION public.update_event_with_audit(
    p_event_id UUID,
    p_tenant_id UUID,
    p_patch JSONB,
    p_actor_member_id UUID
)
RETURNS TABLE (
    id UUID, name TEXT, status TEXT, version INT,
    start_datetime TIMESTAMPTZ, end_datetime TIMESTAMPTZ,
    location_name TEXT, location_address TEXT, location_url TEXT,
    target JSONB, talk_id UUID, prayer_leader_member_id UUID, food_assignment JSONB, updated_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_before JSONB;
  v_row events%ROWTYPE;
BEGIN
  SELECT to_jsonb(e) INTO v_before FROM events e WHERE e.id = p_event_id AND e.tenant_id = p_tenant_id;

  UPDATE events SET
    name                     = COALESCE(p_patch->>'name',                    events.name),
    start_datetime           = COALESCE((p_patch->>'start_datetime')::TIMESTAMPTZ, events.start_datetime),
    end_datetime             = COALESCE((p_patch->>'end_datetime')::TIMESTAMPTZ,   events.end_datetime),
    location_name            = COALESCE(p_patch->>'location_name',          events.location_name),
    location_address         = COALESCE(p_patch->>'location_address',       events.location_address),
    location_url             = CASE WHEN p_patch ? 'location_url' THEN p_patch->>'location_url' ELSE events.location_url END,
    target                   = COALESCE(p_patch->'target',                  events.target),
    talk_id                  = CASE WHEN p_patch ? 'talk_id' THEN (p_patch->>'talk_id')::UUID ELSE events.talk_id END,
    prayer_leader_member_id  = CASE WHEN p_patch ? 'prayer_leader_member_id' THEN (p_patch->>'prayer_leader_member_id')::UUID ELSE events.prayer_leader_member_id END,
    food_assignment          = CASE WHEN p_patch ? 'food_assignment' THEN p_patch->'food_assignment' ELSE events.food_assignment END,
    version                  = events.version + 1,
    updated_at               = now()
  WHERE events.id = p_event_id AND events.tenant_id = p_tenant_id
  RETURNING * INTO v_row;

  PERFORM write_audit_log(p_tenant_id, 'event', v_row.id, 'update', p_actor_member_id, v_before, to_jsonb(v_row));

  RETURN QUERY SELECT
    v_row.id, v_row.name, v_row.status, v_row.version, v_row.start_datetime,
    v_row.end_datetime, v_row.location_name, v_row.location_address, v_row.location_url,
    v_row.target, v_row.talk_id, v_row.prayer_leader_member_id, v_row.food_assignment, v_row.updated_at;
END;
$$;
